#  environment document

name: emgdash
channels:
  - conda-forge
  - resurfemg
dependencies:
  # - python=3.8.6
  - resurfemg=0.0.3
  - dash-bootstrap-components=1.2.0
  - dash=2.5.1
  # - matplotlib=3.3.3
  # - mne=0.21.2
  # - numexpr=2.7.3
  # - numpy=1.22.3
  # - pandas
  - pip=20.2
  # - pyxdf

  - pip:
    
    - dash-uploader==0.6.0

