#  environment document

name: dashboard
channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - dash-bootstrap-components=1.2.0
  - dash=2.5.1
  # - matplotlib=3.3.3
  # - mne=0.21.2
  # - numexpr=2.7.3
  # - numpy=1.22.3
  # - pandas
  - plotly-resampler=0.7.2.2
  - pip=20.2
  # - pyxdf
  - waitress=2.1.2

  - pip:
    - git+https://github.com/ReSurfEMG/ReSurfEMG.git@main

