name: Sanity
on: [push]
jobs:
  # Sanity:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive/ci
  #           --cap-add=SYS_ADMIN
  #           --privileged=true
  #         run: |
  #           set -xe
  #           cd /ci
  #           mkdir -p ./not_pushed/
  #           mount --bind /ReSurfEMG/tests/not_pushed/ ./not_pushed/
  #           python setup.py test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge
          python-version: 3.8
      - run: python3 -m venv .venv
      - run: .venv/bin/python -m pip install wheel
      - run: .venv/bin/python setup.py lint

  